// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fralnpcfktfzvctsdwhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyYWxucGNma3RmenZjdHNkd2h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTk4OTgsImV4cCI6MjA2ODU5NTg5OH0.19arKBqP9yhcCf44zn4BJfcuMzwH7a_MkxK3ve3uOm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});